NetLDAP/ArchitectNetLDAP/Models/LogModel.cs
using System;
using System.Collections.Generic;

namespace ArchitectNetLDAP.Models
{
    public class LogModel
    {
        public LogModel()
        {
            Logs = new List<LogEntry>();
        }
        public List<LogEntry> Logs { get; set; }
    }

    public class LogEntry
    {
        public string Username { get; set; }
        public DateTime LoginDate { get; set; }
    }
}

NetLDAP/ArchitectNetLDAP/Models/LoginModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ArchitectNetLDAP.Models
{
    public class LoginModel
    {
        [Required(ErrorMessage = "Please enter Domain")]
        [Display(Name = "Domain")]
        public string Domain { get; set; }

        [Required(ErrorMessage = "Please enter Username")]
        [Display(Name = "Username")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Please enter Password")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
    }
}

NetLDAP/ArchitectNetLDAP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ArchitectNetLDAP.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public ActionResult Index()
        {
            return View();
        }
	}
}

NetLDAP/ArchitectNetLDAP/Controllers/LogController.cs
using ArchitectNetLDAP.LDAPServiceReference;
using ArchitectNetLDAP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ArchitectNetLDAP.Controllers
{
    public class LogController : Controller
    {
        //
        // GET: /Log/
        public ActionResult Index()
        {
            LogModel model = new LogModel();
            using (var client = new LDAPLoginServiceClient())
            {
                var logs = client.GetLogs();
                model.Logs = logs.Logs.Select(x => new LogEntry { Username = x.Username, LoginDate = x.LoginDate }).ToList();
            }
            return View(model);
        }
    }
}

NetLDAP/ArchitectNetLDAP/Controllers/LoginController.cs
using ArchitectNetLDAP.LDAPServiceReference;
using ArchitectNetLDAP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ArchitectNetLDAP.Controllers
{
    public class LoginController : Controller
    {
        //
        // GET: /Login/
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Login()
        {
            if (String.IsNullOrEmpty(HttpContext.User.Identity.Name))
            {
                FormsAuthentication.SignOut();
                return View();
            }
            return Redirect("/Home");
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(LoginModel model, string returnurl)
        {
            if (ModelState.IsValid)
            {
                bool isAuthenticated = false;

                try
                {
                    using (var client = new LDAPLoginServiceClient())
                    {
                        var response = client.Login(new LoginRequest { Domain = model.Domain, Username = model.Username, Password = model.Password });
                        isAuthenticated = response.IsOK;
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.StackTrace);
                }

                if (isAuthenticated)
                {
                    FormsAuthentication.SetAuthCookie(model.Username, true);                    
                    if (string.IsNullOrEmpty(returnurl))
                        return Json("OK");
                    else
                        return Redirect(returnurl);
                }
                else
                {
                    ModelState.AddModelError("", "Access Denied");
                    return Json("Access Denied");
                }
            }
            return Json("Access Denied");
            //return View(model);
        }

        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login", "Login");
        }
    }
}

NetLDAP/ArchitectNetLDAP/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <h1>Home</h1>
    <div>
        @Html.ActionLink("Login Application", "Index", "Login")
    </div>
    <div>
        @Html.ActionLink("Login Logs Application", "Index", "Log")
    </div>
</body>
</html>

NetLDAP/ArchitectNetLDAP/Views/Log/Index.cshtml
@model ArchitectNetLDAP.Models.LogModel
@{
    ViewBag.Title = "Index";
}

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Logs</title>
</head>
<body>
    <div>
        <ul>
            @if (Model != null)
            {
                if (Model.Logs != null)
                {
                    foreach (var l in Model.Logs)
                    {
<li>@string.Format("{0} : {1}", l.LoginDate.ToString(), l.Username)</li>
                    }
                }
            }
        </ul>
    </div>
</body>
</html>

NetLDAP/ArchitectNetLDAP/Views/Login/Index.cshtml
@model ArchitectNetLDAP.Models.LoginModel

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>
<body>
    <div class="login" style="width: 350px !important; margin: 0 auto; margin-top: 200px;">
        <div class="box">
            <div class="notification tip"><span class="strong">Ldap Login</span>@Html.ValidationSummary(false, "")</div>
            @using (Html.BeginForm("Login", "Login", FormMethod.Post))
            { 
                <div class="form col">
                    <div>
                        @Html.LabelFor(f => f.Domain)
                        @Html.TextBoxFor(f => f.Domain, new { title = "Enter Domain", @Value = @ViewBag.Domain })
                    </div>
                    <div>
                        @Html.LabelFor(f => f.Username)
                        @Html.TextBoxFor(f => f.Username, new { title = "Enter Username", @Value = @ViewBag.Username })
                    </div>
                    <div>
                        @Html.LabelFor(f => f.Password)
                        @Html.PasswordFor(f => f.Password, new { title = "Enter Password.", @Value = @ViewBag.Password })
                    </div>
                    <button type="submit" class="small fr">Login</button><br class="cl" />
                </div>
            }
        </div>
    </div>
</body>
</html>